**Subject Name :** **Introduction to Data Science Lab.** <br>
**Subject Code :** **MCAD191A** <br>
**Topic :** **Data Transformation & Encoding** <br>
**Department of Computer Applications** <br>
**Seacom Skills University**

**Data Transformation** <br>
<p> Data Transformation is the process of converting raw data into a suitable format or structure so that Machine Learning, Deep Learning, and Data Mining algorithms can learn effectively and produce accurate results. <br>
It mainly includes: <br>

*   Feature Scaling (Normalization / Standardization)
*   Encoding Categorical Data

It's needed because,

*   ML models work with numbers, not text.
*   Features must be on comparable scales.
*   Improves model accuracy and convergence.</p>

**Feature Scaling**<br>
**Min-Max Normalization**

In [1]:
#Min–Max Normalization on a Single Column

import numpy as np
import pandas as pd

In [2]:
data = pd.DataFrame({
    "Age": [18, 22, 25, 30, 35, 40, 45, 50]
})

print(data)

   Age
0   18
1   22
2   25
3   30
4   35
5   40
6   45
7   50

In [3]:
data["Age_minmax"] = (
    (data["Age"] - data["Age"].min()) /
    (data["Age"].max() - data["Age"].min())
)

print(data)

   Age  Age_minmax
0   18     0.00000
1   22     0.12500
2   25     0.21875
3   30     0.37500
4   35     0.53125
5   40     0.68750
6   45     0.84375
7   50     1.00000

In [4]:
#Min–Max Normalization on Multiple Columns

data = pd.DataFrame({
    "Age": [18, 22, 25, 30, 35],
    "Fare": [100, 250, 400, 800, 1200]
})

data_minmax = (data - data.min()) / (data.max() - data.min())

print(data_minmax)

        Age      Fare
0  0.000000  0.000000
1  0.235294  0.136364
2  0.411765  0.272727
3  0.705882  0.636364
4  1.000000  1.000000

In [5]:
#Using sklearn
from sklearn.preprocessing import MinMaxScaler

In [6]:
scaler = MinMaxScaler()

data_scaled = scaler.fit_transform(data)

data_scaled = pd.DataFrame(
    data_scaled,
    columns=data.columns
)

print(data_scaled)

        Age      Fare
0  0.000000  0.000000
1  0.235294  0.136364
2  0.411765  0.272727
3  0.705882  0.636364
4  1.000000  1.000000

In [7]:
#With Custom Range
scaler = MinMaxScaler(feature_range=(0, 10))
data_scaled = scaler.fit_transform(data)

print(data_scaled)

[[ 0.          0.        ]
 [ 2.35294118  1.36363636]
 [ 4.11764706  2.72727273]
 [ 7.05882353  6.36363636]
 [10.         10.        ]]

**Z-score Normalization**

In [8]:
#on a Single Column
data2 = pd.DataFrame({
    "Age": [18, 22, 25, 30, 35, 40, 45, 50]
})

print(data2)

   Age
0   18
1   22
2   25
3   30
4   35
5   40
6   45
7   50

In [9]:
mean_age = data2["Age"].mean()
std_age = data2["Age"].std()

data2["Age_zscore"] = (data2["Age"] - mean_age) / std_age

print(data2)

   Age  Age_zscore
0   18   -1.330302
1   22   -0.978486
2   25   -0.714625
3   30   -0.274856
4   35    0.164913
5   40    0.604683
6   45    1.044452
7   50    1.484221

In [10]:
#on Multiple Columns
data3 = pd.DataFrame({
    "Age": [18, 22, 25, 30, 35],
    "Fare": [100, 250, 400, 800, 1200]
})

data_zscore = (data3 - data3.mean()) / data3.std()

print(data_zscore)

        Age      Fare
0 -1.199251 -1.006231
1 -0.599625 -0.670820
2 -0.149906 -0.335410
3  0.599625  0.559017
4  1.349157  1.453444

In [11]:
#Using sklearn
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

data_scaled = scaler.fit_transform(data2)

data_scaled = pd.DataFrame(
    data_scaled,
    columns=data2.columns
)

print(data_scaled)

        Age  Age_zscore
0 -1.422152   -1.422152
1 -1.046046   -1.046046
2 -0.763966   -0.763966
3 -0.293833   -0.293833
4  0.176300    0.176300
5  0.646433    0.646433
6  1.116566    1.116566
7  1.586699    1.586699

**One-Hot Encoding**

In [13]:
#on Single Categorical Column

data4 = pd.DataFrame({
    "Gender": ["Male", "Female", "Female", "Male", "Other"]
})

print(data4)

   Gender
0    Male
1  Female
2  Female
3    Male
4   Other

In [14]:
encoded_data = pd.get_dummies(data4, columns=["Gender"])
print(encoded_data)

   Gender_Female  Gender_Male  Gender_Other
0          False         True         False
1           True        False         False
2           True        False         False
3          False         True         False
4          False        False          True

In [15]:
#with Multiple Categorical Columns

data5 = pd.DataFrame({
    "City": ["Delhi", "Mumbai", "Delhi", "Kolkata"],
    "Department": ["HR", "IT", "Finance", "IT"]
})

encoded_data = pd.get_dummies(data5)
print(encoded_data)

   City_Delhi  City_Kolkata  City_Mumbai  Department_Finance  Department_HR  \
0        True         False        False               False           True
1       False         False         True               False          False
2        True         False        False                True          False
3       False          True        False               False          False

   Department_IT
0          False
1           True
2          False
3           True

In [16]:
#using sklearn
from sklearn.preprocessing import OneHotEncoder

In [17]:
data6 = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Red"]
})

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(data6[["Color"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["Color"])
)

print(encoded_df)

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0

**Applying Normalization & One-Hot Encoding on Titanic Dataset**

In [18]:
titanic = pd.read_csv("/content/titanic.csv")

In [19]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [21]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [22]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
titanic["Age"] = titanic["Age"].fillna(titanic["Age"].median())
titanic["Cabin"] = titanic["Cabin"].fillna(titanic["Cabin"].mode()[0])
titanic["Embarked"] = titanic["Embarked"].fillna(titanic["Embarked"].mode()[0])

In [24]:
titanic.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [25]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S

In [26]:
#Feature Scaling using Pandas
#Min-Max Normalization

titanic["Age_minmax"] = (titanic["Age"] - titanic["Age"].min()) / \
                     (titanic["Age"].max() - titanic["Age"].min())

titanic["Fare_minmax"] = (titanic["Fare"] - titanic["Fare"].min()) / \
                      (titanic["Fare"].max() - titanic["Fare"].min())

titanic[["Age", "Age_minmax", "Fare", "Fare_minmax"]].head()

    Age  Age_minmax     Fare  Fare_minmax
0  22.0    0.271174   7.2500     0.014151
1  38.0    0.472229  71.2833     0.139136
2  26.0    0.321438   7.9250     0.015469
3  35.0    0.434531  53.1000     0.103644
4  35.0    0.434531   8.0500     0.015713

In [27]:
#Feature Scaling using Scikit-learn
#Min-Max Scaling

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

titanic[["Age_scaled", "Fare_scaled"]] = scaler.fit_transform(
    titanic[["Age", "Fare"]]
)

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_minmax,Fare_minmax,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S,0.271174,0.014151,0.271174,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.472229,0.139136,0.472229,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S,0.321438,0.015469,0.321438,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.434531,0.103644,0.434531,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S,0.434531,0.015713,0.434531,0.015713

In [28]:
#Z-Score Normalization
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

titanic[["Age_std", "Fare_std"]] = std_scaler.fit_transform(
    titanic[["Age", "Fare"]]
)

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_minmax,Fare_minmax,Age_scaled,Fare_scaled,Age_std,Fare_std
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,B96 B98,S,0.271174,0.014151,0.271174,0.014151,-0.565736,-0.502445
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.472229,0.139136,0.472229,0.139136,0.663861,0.786845
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,B96 B98,S,0.321438,0.015469,0.321438,0.015469,-0.258337,-0.488854
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.434531,0.103644,0.434531,0.103644,0.433312,0.420730
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,B96 B98,S,0.434531,0.015713,0.434531,0.015713,0.433312,-0.486337

In [29]:
#Label Encoding
titanic["Sex_label"] = titanic["Sex"].map({"male": 1, "female": 0})
titanic[["Sex", "Sex_label"]].head()

      Sex  Sex_label
0    male          1
1  female          0
2  female          0
3  female          0
4    male          1

In [30]:
titanic["Embarked_label"] = titanic["Embarked"].map({"S": 0, "C": 1, "Q": 2})
titanic[["Embarked", "Embarked_label"]].head()

  Embarked  Embarked_label
0        S               0
1        C               1
2        S               0
3        S               0
4        S               0

In [31]:
#Encoding using Scikit-learn
#One-Hot Encoding

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(titanic[["Sex", "Embarked"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["Sex", "Embarked"])
)

encoded_df.head()

   Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0         0.0       1.0         0.0         0.0         1.0
1         1.0       0.0         1.0         0.0         0.0
2         1.0       0.0         0.0         0.0         1.0
3         1.0       0.0         0.0         0.0         1.0
4         0.0       1.0         0.0         0.0         1.0