**Subject Name :** **Introduction to Data Science Lab.** <br>
**Subject Code :** **MCAD191A** <br>
**Topic :** **Pandas** <br>
**Department of Computer Applications** <br>
**Seacom Skills University**

<p>Pandas is a popular open-source Python library used for data manipulation, analysis, and cleaning. <br>
It is especially valuable in data science, machine learning, and analytics projects. <br>
Pandas provides powerful data structures (Series and DataFrame) for handling structured (tabular) data, similar to Excel or SQL tables.</p>

**Installation**

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

**Importing Pandas**

In [2]:
import pandas as pd

**Series**
<p>A one-dimensional labeled array, similar to a column in Excel.</p>

In [3]:
#Creating a Series(1D Data)
import pandas as pd

s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

**Series from a List of Strings**

In [4]:
names = ["Virat", "Sachin", "Rohit"]
series_names = pd.Series(names, name = "Player Names")
print(series_names)

0     Virat
1    Sachin
2     Rohit
Name: Player Names, dtype: object

**Series from a List of Integers**

In [5]:
runs = [85, 92, 78]
series_runs = pd.Series(runs, name = "Runs")
print(series_runs)

0    85
1    92
2    78
Name: Runs, dtype: int64

**Series from a Custom List**

In [6]:
players = [("Virat", 85), ("Sachin", 92), ("Rohit", 78)]
series_players = pd.Series(players, name="Player (Name, Runs)")
print(series_players)

0     (Virat, 85)
1    (Sachin, 92)
2     (Rohit, 78)
Name: Player (Name, Runs), dtype: object

**Setting a Custom Index and Name**

In [7]:
series_custom = pd.Series(runs, index=names, name="Player Scores")
print(series_custom)

Virat     85
Sachin    92
Rohit     78
Name: Player Scores, dtype: int64

**Series from Dictonary**

In [8]:
data = {"a": 10, "b": 20, "c": 30}
s = pd.Series(data)
print(s)

a    10
b    20
c    30
dtype: int64

**Series from dict with custom index order**

In [9]:
data = {"a": 10, "b": 20, "c": 30}
s = pd.Series(data, index=["b", "c", "a"])
print(s)

b    20
c    30
a    10
dtype: int64

In [10]:
data = {"a": 10, "b": 20, "c": 30}
s = pd.Series(data, index=["b", "c", "d", "a"])
print(s)

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

**Setting a name for the Series**

In [11]:
subjects = {"Math": 85, "Science": 92, "English": 78}
marks = pd.Series(subjects, name="Student Marks")
print(marks)
print("Series name:", marks.name)

Math       85
Science    92
English    78
Name: Student Marks, dtype: int64
Series name: Student Marks

**Series Attributes**

In [12]:
s = pd.Series([10, 20, 20, 40], name="Marks")
print(s)

0    10
1    20
2    20
3    40
Name: Marks, dtype: int64

In [13]:
#size
#It returns the number of elements in the Series
print(s.size)

4

In [14]:
#dtype
#It returns the data type of the Series elements
print(s.dtype)

int64

In [15]:
#name
#It returns the name of the Series
print(s.name)

Marks

In [16]:
s.name = "Student Marks"
print(s.name)

Student Marks

In [17]:
#is_unique
# It checks whether all elements in Series are unique
print(s.is_unique)

False

In [18]:
#index
#It gives the index labels of the Series
print(s.index)

RangeIndex(start=0, stop=4, step=1)

In [19]:
#index values
print(list(s.index))

[0, 1, 2, 3]

In [20]:
#values
#It returns the Series values as a NumPy array
print(s.values)

[10 20 20 40]

**Pandas DataFrame**<br>
<p>A two-dimensional, size-mutable, and heterogeneous tabular data structure with labeled axes (rows and columns).</p>

In [21]:
#Creating a DataFrame(2D Table)

data = {
    "Name": ["Virat", "Sachin", "Rohit"],
    "Age": [37, 52, 38],
    "Runs": [85, 90, 95]
}

df = pd.DataFrame(data)
print(df)

     Name  Age  Runs
0   Virat   37    85
1  Sachin   52    90
2   Rohit   38    95

**Viewing and Inspecting Data**

In [22]:
#printing first 5 rows
df.head()

     Name  Age  Runs
0   Virat   37    85
1  Sachin   52    90
2   Rohit   38    95

In [23]:
#printing last 5 rows
df.tail()

     Name  Age  Runs
0   Virat   37    85
1  Sachin   52    90
2   Rohit   38    95

In [24]:
#printing info about columns, data types, nulls
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Runs    3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [25]:
#printing summary for numerical columns
df.describe()

             Age  Runs
count   3.000000   3.0
mean   42.333333  90.0
std     8.386497   5.0
min    37.000000  85.0
25%    37.500000  87.5
50%    38.000000  90.0
75%    45.000000  92.5
max    52.000000  95.0

In [26]:
#printing rows & columns count
df.shape

(3, 3)

In [27]:
#printing list of column names
df.columns

Index(['Name', 'Age', 'Runs'], dtype='object')

In [28]:
#printing data types of each column
df.dtypes

Name    object
Age      int64
Runs     int64
dtype: object

**Selecting Data (Indexing)**

In [29]:
#selecting a single column
df["Name"]

0     Virat
1    Sachin
2     Rohit
Name: Name, dtype: object

In [30]:
#selecting multiple columns
df[["Name", "Runs"]]

     Name  Runs
0   Virat    85
1  Sachin    90
2   Rohit    95

In [31]:
#selecting row by label
df.loc[1]

Name    Sachin
Age         52
Runs        90
Name: 1, dtype: object

In [32]:
#selecting row by index
df.iloc[2]

Name    Rohit
Age        38
Runs       95
Name: 2, dtype: object

In [33]:
#selecting specific row & column
df.loc[0, "Age"]

np.int64(37)

**Filtering Rows**

In [34]:
#using conditions
df[df["Runs"] > 90]

    Name  Age  Runs
2  Rohit   38    95

In [35]:
#multiple conditions
df[(df["Age"] > 25) & (df["Runs"] > 90)]

    Name  Age  Runs
2  Rohit   38    95

**Adding & Removing Columns**

In [36]:
#adding new column
df["Strike Rate"] = ["106.25", "122", "120"]

In [37]:
print(df)

     Name  Age  Runs Strike Rate
0   Virat   37    85      106.25
1  Sachin   52    90         122
2   Rohit   38    95         120

In [38]:
#dropping a column
df.drop("Strike Rate", axis=1, inplace=True)

In [39]:
print(df)

     Name  Age  Runs
0   Virat   37    85
1  Sachin   52    90
2   Rohit   38    95

**Adding & Removing Rows**

In [40]:
#adding a new row
new_row = {"Name": "David", "Age": 22, "Runs": 88}

#Converting the new row to a DataFrame before concatenating
new_row_df = pd.DataFrame([new_row])
df = pd.concat([df, new_row_df], ignore_index=True)

In [41]:
print(df)

     Name  Age  Runs
0   Virat   37    85
1  Sachin   52    90
2   Rohit   38    95
3   David   22    88

In [42]:
#dropping row by index
df.drop(1, axis=0, inplace=True)

In [43]:
print(df)

    Name  Age  Runs
0  Virat   37    85
2  Rohit   38    95
3  David   22    88

**Handling Missing Data**

In [44]:
#finding missing values
df.isnull()

    Name    Age   Runs
0  False  False  False
2  False  False  False
3  False  False  False

In [45]:
df.isnull().sum()

Name    0
Age     0
Runs    0
dtype: int64

In [46]:
#filling missing values
df.fillna(0)

    Name  Age  Runs
0  Virat   37    85
2  Rohit   38    95
3  David   22    88

In [47]:
#dropping rows with missing values
df.dropna()

    Name  Age  Runs
0  Virat   37    85
2  Rohit   38    95
3  David   22    88

**Sorting Data**

In [48]:
#sorting by values
df.sort_values("Runs")

    Name  Age  Runs
0  Virat   37    85
3  David   22    88
2  Rohit   38    95

In [49]:
#sorting by descending
df.sort_values("Runs", ascending=False)

    Name  Age  Runs
2  Rohit   38    95
3  David   22    88
0  Virat   37    85

In [50]:
#sorting by index
df.sort_index()

    Name  Age  Runs
0  Virat   37    85
2  Rohit   38    95
3  David   22    88

**Grouping & Aggregation**

In [51]:
#group by a column
df.groupby("Age")["Runs"].mean()

Age
22    88.0
37    85.0
38    95.0
Name: Runs, dtype: float64

In [52]:
#multiple functions
df.groupby("Age").agg({"Runs": ["mean", "max", "min"]})

     Runs
     mean max min
Age
22   88.0  88  88
37   85.0  85  85
38   95.0  95  95

**Merging, Joining, Concatenating DataFrames**

In [53]:
data = {
    "Name": ["Hardik", "Subhman", "Sreyas"],
    "Age": [30, 28, 29],
    "Runs": [85, 90, 95]
}

df1 = pd.DataFrame(data)
print(df1)

      Name  Age  Runs
0   Hardik   30    85
1  Subhman   28    90
2   Sreyas   29    95

In [54]:
data = {
    "Name": ["Rahul", "Bumrah", "Jadeja"],
    "Age": [34, 30, 35],
    "Runs": [63, 12, 88]
}

df2 = pd.DataFrame(data)
print(df2)

     Name  Age  Runs
0   Rahul   34    63
1  Bumrah   30    12
2  Jadeja   35    88

In [55]:
#concatenate
pd.concat([df1, df2])

      Name  Age  Runs
0   Hardik   30    85
1  Subhman   28    90
2   Sreyas   29    95
0    Rahul   34    63
1   Bumrah   30    12
2   Jadeja   35    88

In [56]:
#merge (SQL JOIN)
pd.merge(df1, df2, on="Age")

   Name_x  Age  Runs_x  Name_y  Runs_y
0  Hardik   30      85  Bumrah      12

In [57]:
#join
pd.DataFrame(df1).join(pd.DataFrame(df2), lsuffix="_df1", rsuffix="_df2")

  Name_df1  Age_df1  Runs_df1 Name_df2  Age_df2  Runs_df2
0   Hardik       30        85    Rahul       34        63
1  Subhman       28        90   Bumrah       30        12
2   Sreyas       29        95   Jadeja       35        88

**Reading & Writing Files**

In [58]:
#reading CSV file
df = pd.read_csv("/drug200.csv")

In [59]:
#reading Excel file
df = pd.read_excel("/drug200.xls")

In [60]:
#write to CSV
#df.to_csv("output.csv", index=False)

In [61]:
#Write to Excel
#df.to_excel("output.xlsx", index=False)

**Statistical Operations**

In [62]:
print(df1["Runs"].mean())
print(df1["Runs"].median())
print(df1["Runs"].max())
print(df1["Runs"].min())
print(df1["Runs"].std())
print(df1["Runs"].sum())

90.0
90.0
95
85
5.0
270

**Creating DataFrame in Various Ways**

In [63]:
#from dictionary of lists
pd.DataFrame({"A":[1,2], "B":[3,4]})

   A  B
0  1  3
1  2  4

In [64]:
#from list of dictionaries
pd.DataFrame([{"A":1,"B":3}, {"A":2,"B":4}])

   A  B
0  1  3
1  2  4

In [65]:
#from Series
pd.DataFrame({"Age": pd.Series([24,30,28])})

   Age
0   24
1   30
2   28